language: node_js
sudo: true
dist: trusty
node_js:
  - '6.9.5'

addons:
  chrome: stable

before_install:
  - export CHROME_BIN=chromium_browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  - npm install -g @angular/cli rollup karma
  - npm install

script:
  - ./build.sh
  - karma start karma.conf.js --single-run
