language: node_js
sudo: true
dist: trusty
node_js:
  - '6.9.5'

addons:
  chrome: stable

install:
  - npm install -g @angular/cli rollup
  - npm install
  - sh -e /etc/init.d/xvfb start # start xvfb for local chrome testing

script:
  - ./build.sh
  - ng test
